services:
  postgres-db:
    image: postgres:18-alpine
    container_name: universal_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: default_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: universal_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres-db

volumes:
  pgdata: